import_from_git(url: 'https://github.com/marcelo-schroeder/IFAFastfile.git')

platform :ios do
    override_lane :updateDependencies do
        cocoapods
        carthage
    end
    lane :crap do
        puts File.join(File.basename(Dir.getwd), '*.podspec')
    end
end